default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Davidrama
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: Blogs-Development

test:
  <<: *default
  database: Blogs-Test

production:
  <<: *default
  database: Blogs-Production
