default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Davidrama
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: Lanzz-Blog-1

test:
  <<: *default
  database: Lanzz-Blog-2

production:
  <<: *default
  database: Lanzz-Blog-3
