# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Davidrama
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: Lanzz-Blog-Development

  test:
  <<: *default
  database: Lanzz-Blog-Test

production:
  <<: *default
  database: Lanzz-Blog-Production
